---
title: Chris Wijnia / designer & developer
timezone: Europe/Amsterdam
collections:
  includes:
    title: Includes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
title_html: Chris Wijnia <small><span>/</span> designer &amp; developer</small>
header_img: "/assets/img/travel.jpg"
header_video: "/assets/img/travel.mp4"
share_img: "/assets/img/og_img.jpg"
description: Hi, my name is Chris. I currently work for Boerdam - a digital agency
  based in The Netherlands. I design and code things.
description_html: "Hi, my name is <a href=\"javascript:\" class=\"show-img\">Chris<img
  data-src=\"assets/img/avatar.png\"></a>. \nI currently work for <a class=\"show-img\"
  href=\"//boerdam.nl\">Boerdam<img data-src=\"/assets/img/gifs/boerdam.png\"></a>\n-
  a digital agency based in The Netherlands.\nI design and code things. When I'm not
  working on something tech-related I like to spend my time traveling, playing\n<a
  href=\"//lichess.org/@/christhebutcher\" class=\"show-img\">chess<img data-src=\"/assets/img/gifs/chess.gif\"></a>
  or taking\n<a href=\"//instagram.com/christhebutcher\" class=\"show-img\">photos<img
  src=\"/assets/img/gifs/photo.gif\"></a>."
email: ccwijnia@gmail.com
baseurl: 
url: http://www.chriswijnia.com
twitter_username: christianwijnia
github_username: christhebutcher
markdown: kramdown
include:
- _pages
plugins:
- jekyll-feed
