---
title: Christian Wijnia
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: designer & developer
email: christian@boerdam.nl
description: Christian Wijnia / designer & developer
baseurl: 
url: http://christhebutcher.github.io
twitter_username: chriswijnia
github_username: christhebutcher
boerdam_username: christian
markdown: kramdown
gems:
- octopress-autoprefixer
babel_js_extensions: es6
exclude:
- node_modules
- gulpfile.js
- package.json
