---
title: Chris Wijnia / designer & developer
timezone: Europe/Amsterdam
collections:
  includes:
    title: Includes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
title_html: Chris Wijnia <small><span>/</span> designer &amp; developer</small>
email: ccwijnia@gmail.com
header_img: 
header_video: "/assets/img/travel.mp4"
description: "Hi, my name is <a href=\"#\" class=\"show-img\">Chris<img src=\"assets/img/avatar.png\"></a>.
  \nI currently work for <a class=\"show-img\" href=\"//boerdam.nl\">Boerdam<img src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDRaI_YYthKoGMmDqfiaRvcWsLsZGj46485MkHdPN07cnTsYfF\"></a>\n-
  a digital agency based in The Netherlands.\nI design and code things. When I'm not
  working on something tech-related I like to spend my time traveling, playing\n<a
  href=\"//lichess.org/@/christhebutcher\" class=\"show-img\">chess<img src=\"https://media.giphy.com/media/TfEKpBU9RaYrC/giphy.gif\"></a>
  or taking\n<a href=\"//instagram.com/christhebutcher\" class=\"show-img\">photos<img
  src=\"https://media.giphy.com/media/3owypf6HrM3J7UTvAA/giphy.gif\"></a>."
baseurl: 
url: chriswijnia.com
twitter_username: christianwijnia
github_username: christhebutcher
markdown: kramdown
include:
- _pages
plugins:
- jekyll-feed
