---
title: Chris Wijnia / designer & developer
timezone: Europe/Amsterdam
collections:
  includes:
    title: Includes
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ccwijnia@gmail.com
description: "\n"
baseurl: 
url: chriswijnia.com
twitter_username: christianwijnia
github_username: christhebutcher
markdown: kramdown
include:
- _pages
plugins:
- jekyll-feed
