# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christian Wijnia
subtitle: Interaction Designer
email: christian@boerdam.nl
description: Christian Wijnia - Interaction Designer @ boerdam.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://christhebutcher.github.io/ixd" # the base hostname & protocol for your site
twitter_username: chriswijnia
github_username:  christhebutcher
boerdam_username: christian

# Build settings
markdown: kramdown

gems: 
  - octopress-autoprefixer
  - jekyll-babel
  
babel_js_extensions: 'es6'